[package]
name = "shader_so_cool"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
winit = "0.25"
cgmath = { version = "0.18", features = [ "serde" ] }
env_logger = "0.8"
log = "0.4"
wgpu = "0.11.0"
futures = "0.3.14"
bytemuck = { version = "1.7.0", features = [ "derive" ] }
rand = "0.8.4"
rayon = "1.5.1"
anyhow = "1.0.42"
fs_extra = "1.2.0"
weresocool = { path = "../weresocool" }
serde = { version = "1.0.119", features = ["derive"] }
serde_json = "1.0.64"
crossbeam-channel = "0.5.1"
rodio = "0.14.0"
shaderc = "0.7.2"
async-trait = "0.1.51"
egui = "0.14.2"
egui_wgpu_backend = "0.13.0"
egui_winit_platform = { path = "./egui_winit_platform" }
chrono = "0.4.19"
epi = "0.14.0"
kintaro_egui_lib = { version = "0.14.0", path = "egui_lib" }
dyn-clone = "1.0.4"
hex = "0.4.3"

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"
rayon = "1.4"
shaderc = "0.7"
