[package]
name = "shader_so_cool"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
winit = "0.24"
cgmath = "0.18"
env_logger = "0.8"
log = "0.4"
wgpu = "0.9.0"
futures = "0.3.14"
bytemuck = { version = "1.7.0", features = [ "derive" ] }
rand = "0.8.4"
rayon = "1.5.1"
anyhow = "1.0.42"
fs_extra = "1.2.0"

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"
rayon = "1.4"
shaderc = "0.7"
