[package]
name = "kintaro_egui_lib"
version = "0.14.0"
authors = ["Danny Meyer <kintaro@xasopheno.com"]
description = "Kintaro Egui"
edition = "2018"
homepage = ""
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = ""
categories = ["gui", "graphics"]
keywords = ["egui", "gui", "gamedev"]

[package.metadata.docs.rs]
all-features = true

[lib]

[dependencies]
egui = { version = "0.14.0", default-features = false }
epi = { version = "0.14.0" }
unicode_names2 = { version = "0.4.0", default-features = false }

# feature "http":
ehttp = { version = "0.1.0", optional = true }
image = { version = "0.23", default-features = false, features = ["jpeg", "png"], optional = true }

serde = { version = "1.0.130", features = ["derive"] }

[dev-dependencies]
criterion = { version = "0.3", default-features = false }

[features]
default = []
http = ["ehttp", "image"]
persistence = ["egui/persistence", "epi/persistence"]

# Enable additional checks if debug assertions are enabled (debug builds).
extra_debug_asserts = ["egui/extra_debug_asserts"]
# Always enable additional checks.
extra_asserts = ["egui/extra_asserts"]
